
import Head from 'next/head'
import styles from '../styles/Main.module.css'
import Navbar from './Components/Layout/Navbar'
import Footer from './Components/Layout/Footer'
import HomeComponent from './Components/HomeComponent'

export default function Home( ) {

  return (
    <div className={styles.container}>
      <Head>
        <title>smart-farm</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
      
      <main className={styles.main}>
        <HomeComponent />
      </main>

      <footer className={styles.footer}>
        <Footer />
      </footer>
    </div>
  )
}
