import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from './Components/Navbar'
import HomeComponent from './Components/Home'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>smart-farm</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />

      <main className={styles.main}>
        <HomeComponent />
      </main>

      <footer className={styles.footer}>
        Powered by{' '}
        <span className={styles.logo}>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span>
      </footer>
    </div>
  )
}
